import { projects } from './data/projects.js?v=projects-2';

const groups = { Languages: ['Python','Java','C++','C#','JavaScript','PHP','SQL'], 'Web + APIs': ['HTML','CSS','REST APIs','FastAPI','WebSockets'], Systems: ['Linux','Ubuntu Server','nginx','Cloudflare','Networking','SSH','PostgreSQL'], 'Automation + Platforms': ['Power Automate','Canvas LMS APIs','Git','GitHub'], Security: ['Secure configuration','Privacy-aware processing','Access control','Threat-conscious design'] };
const categories = ['All', ...new Set(projects.map(p => p.category))]; let active = 'All';
const grid = document.querySelector('#project-grid'); const filters = document.querySelector('#filters'); const search = document.querySelector('#project-search');
const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
categories.forEach(name => { const b=document.createElement('button'); b.textContent=name; b.className=name==='All'?'active':''; b.addEventListener('click',()=>{active=name; filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();}); filters.append(b); });
function render(){ const q=search.value.trim().toLowerCase(); const shown=projects.filter(p=>(active==='All'||p.category===active)&&(!q||[p.title,p.summary,p.category,...p.tech].join(' ').toLowerCase().includes(q))); grid.innerHTML=shown.map((p,i)=>`<article class="project-card reveal visible ${p.featured?'featured':''}" style="--i:${i}"><a href="/project.html?id=${encodeURIComponent(p.slug)}" aria-label="View ${esc(p.title)} case study"><div class="project-media ${p.image?'has-image':'generated'}">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.title)} project preview" loading="lazy">`:`<div class="project-glyph" aria-hidden="true">${String(i+1).padStart(2,'0')}<span></span></div>`}<span class="card-status">${esc(p.status)}</span></div><div class="project-info"><div><p>${esc(p.category)} · ${esc(p.year)}</p><h3>${esc(p.title)}</h3></div><span class="arrow">↗</span><p class="summary">${esc(p.summary)}</p><div class="tags">${p.tech.slice(0,4).map(t=>`<span>${esc(t)}</span>`).join('')}</div></div></a></article>`).join(''); document.querySelector('#no-results').hidden=shown.length>0; }
search.addEventListener('input',render); render();
document.querySelector('#skill-groups').innerHTML=Object.entries(groups).map(([k,v],i)=>`<article class="skill-group reveal"><span>0${i+1}</span><h3>${k}</h3><div>${v.map(x=>`<b>${x}</b>`).join('')}</div></article>`).join('');
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.12}); document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const menu=document.querySelector('.menu-button'),nav=document.querySelector('#nav'); menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);}); nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false');}));
document.querySelector('#year').textContent=new Date().getFullYear();
if(matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`);});}
const canvas=document.querySelector('#network'); const ctx=canvas.getContext('2d'); let nodes=[]; function size(){const d=Math.min(devicePixelRatio,1.5);canvas.width=canvas.clientWidth*d;canvas.height=canvas.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);nodes=Array.from({length:matchMedia('(max-width:700px)').matches?18:34},()=>({x:Math.random()*canvas.clientWidth,y:Math.random()*canvas.clientHeight,vx:(Math.random()-.5)*.14,vy:(Math.random()-.5)*.14}));} function draw(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);nodes.forEach((n,i)=>{n.x+=n.vx;n.y+=n.vy;if(n.x<0||n.x>canvas.clientWidth)n.vx*=-1;if(n.y<0||n.y>canvas.clientHeight)n.vy*=-1;for(let j=i+1;j<nodes.length;j++){const m=nodes[j],d=Math.hypot(n.x-m.x,n.y-m.y);if(d<150){ctx.strokeStyle=`rgba(75,180,255,${(1-d/150)*.16})`;ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(m.x,m.y);ctx.stroke();}}ctx.fillStyle='rgba(111,215,255,.5)';ctx.beginPath();ctx.arc(n.x,n.y,1.2,0,7);ctx.fill();});requestAnimationFrame(draw);} size();addEventListener('resize',size);draw();
