import { projects } from './data/projects.js?v=project-visuals-1';
const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const visualMarkup=kind=>{
  if(kind==='canvas')return `<div class="project-visual canvas-visual" aria-label="Illustration of bulk Canvas course operations"><div class="visual-window"><div class="window-bar"><i></i><i></i><i></i><b>COURSE OPERATIONS</b></div><div class="canvas-command"><span>FIND</span><strong>outdated content</strong><i>→</i><span>REPLACE</span></div><div class="course-rows"><span><i></i><b>COURSE_101</b><em>READY</em></span><span><i></i><b>COURSE_204</b><em>SCAN</em></span><span><i></i><b>COURSE_318</b><em>READY</em></span></div></div></div>`;
  if(kind==='redaction')return `<div class="project-visual redaction-visual" aria-label="Illustration of a local document redaction scan"><div class="document-scan"><div class="doc-label"><span>PII_SCAN</span><b>LOCAL</b></div><p><i></i><i class="redacted"></i><i></i></p><p><i class="short"></i><i></i><i class="redacted wide"></i></p><p><i></i><i class="redacted"></i><i class="short"></i></p><p><i class="redacted wide"></i><i></i></p><div class="scan-beam"></div><div class="scan-count">03 NAMES DETECTED</div></div></div>`;
  if(kind==='homelab')return `<div class="project-visual homelab-visual" aria-label="Illustration of connected homelab infrastructure"><div class="network-cloud">CF</div><div class="network-line line-one"></div><div class="network-line line-two"></div><div class="server-rack"><div><i></i><span>NGINX</span><b>●</b></div><div><i></i><span>APPS</span><b>●</b></div><div><i></i><span>DATA</span><b>●</b></div></div><div class="service-nodes"><i></i><i></i><i></i></div></div>`;
  return '';
};
const id=new URLSearchParams(location.search).get('id'); const p=projects.find(x=>x.slug===id); const main=document.querySelector('#project-detail');
if(!p){document.title='Project not found — Kolton Galie';main.innerHTML='<section class="detail-empty"><p class="kicker">404 / Project</p><h1>That case study is not here.</h1><a class="button primary" href="/#work">Return to projects</a></section>';} else {const hasPublic=p.github||p.resources?.length;document.title=`${p.title} — Kolton Galie`;document.querySelector('meta[name="description"]').content=p.summary;main.innerHTML=`<section class="detail-hero"><div><p class="kicker">${esc(p.category)} / ${esc(p.year)}</p><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p><div class="tags">${p.tech.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><aside><span>Status</span><strong>${esc(p.status)}</strong><span>Public work</span><strong>${hasPublic?'Available':'Not publicly available'}</strong></aside></section><section class="detail-visual">${p.video?`<video controls muted playsinline poster="${esc(p.image||'')}"><source src="${esc(p.video)}" type="video/mp4"></video>`:p.image?`<img src="${esc(p.image)}" alt="${esc(p.title)} project preview">`:p.visual?visualMarkup(p.visual):`<div class="architecture" aria-label="Conceptual workflow"><span>INPUT</span><i>→</i><span>PROCESS</span><i>→</i><span>OUTPUT</span></div>`}</section><section class="detail-content"><article><p class="kicker">The system</p><h2>Why it exists</h2><p class="large">${esc(p.description)}</p></article><article><p class="kicker">What it does</p><h2>Core capabilities</h2><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></article><article><p class="kicker">Engineering note</p><h2>The interesting part</h2><p>${esc(p.challenge)}</p></article><article class="source-note"><p class="kicker">Public work</p><h2>${p.github?'Inspect the source':p.resources?.length?'Tools and write-ups':'Source is not published'}</h2><p>${p.github?'The repository contains setup and architecture documentation.':p.resources?.length?'These tools are published through the Instructure Community with implementation details and downloadable scripts.':'No verified publishable source tree was found on this server. A public URL will be added only after the real code is reviewed, sanitized, and published.'}</p>${p.github?`<a class="button primary" href="${esc(p.github)}" target="_blank" rel="noopener noreferrer">View on GitHub ↗</a>`:p.resources?.map(r=>`<a class="button resource-button" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.label)} ↗</a>`).join('')||'<span class="button disabled" aria-disabled="true">Public link pending review</span>'}</article></section><nav class="next-project"><span>Continue exploring</span><a href="/project.html?id=${encodeURIComponent(projects[(projects.indexOf(p)+1)%projects.length].slug)}">Next case study <b>→</b></a></nav>`;}
document.querySelector('#year').textContent=new Date().getFullYear();
